
[http]
bind_addr = "0.0.0.0"
bind_port = 3000
max_body_size = "64KiB"
request_timeout = "2s"

[http.routes]
metrics = /metrics
liveness = /live


#
# OIDC Configuration
#
# In the IO zone we use keycloak and the "one-environment-pkce" client_id.
# The client secret 
#
[http.auth.oidc]
issuer_url = "https://keycloak.pictet.aws/realms/pictet"
client_id = "one-environment-pkce"
client_secret = "{{ OIDC_SECRET }}"
callback_url = "http://localhost:3000/auth/callback"
state = true
pkce = true

[database]
url = "postgres://postgres:postgres@localhost:5432/postgres"
max_pool_size = 2

[log]
format = "json"