name: Greetings

on: [pull_request_target, issues, workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:        
    - name: Echo username
      shell: bash
      run: |
        echo "Hello, ${{ github.actor }}!"
        
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome ${{ github.actor }} to the project!"
        pr-message: "Welcome ${{ github.actor }} to the project!"